### PR TITLE
Correct the Vendor remote repo!

### PR DESCRIPTION
**Pull request by DroidThug**

### CODE REVIEW

**Comment by h2o64** [comment]
Does this branch exists?

**Comment by DroidThug** [comment]
@h2o64 Sure it does exist, to us noobs who'd like to check stuff out :dancers:

**Comment by h2o64** [comment]
It's just my challenge's product

**Comment by DroidThug** [comment]
Okay Sir! I just noticed an error, so I just created a PR! Nvm :P

**Comment by h2o64** [comment]
I'll merge it don't worry

**Pull request merged**
